In [6]:
import os, sys
script_dir = os.getcwd()
module_path = script_dir
for _ in range(1):
    module_path = os.path.abspath(os.path.join(module_path, '../'))
    if module_path not in sys.path:
        sys.path.insert(0,module_path)

from src import decode_moddeling, prefill_moddeling

import pandas as pd
from plotnine import *
import plotnine as p9
from src.system import System
import pandas as pd
from src.analye_model import *
import plotly.graph_objects as go
import plotly.express as px

In [7]:
model_df, summary_table = decode_moddeling(model = 'mixtral_7x8', batch_size = 1, Bb = 1 ,
                            input_tokens = 1024, output_tokens = 256, model_profilling=True,
                            tensor_parallel = 1, pipeline_parallel = 1, debug=True) 
display(model_df)
display(summary_table)

/Users/abambhaniya3/GenZ/src/LLM_inference/llm_decode.py:108: UserWarning: All params would not fit on chip. System Memory Cap:40.0 GB , Weights : 86.5 GB, KV Cache:0.15625

,Op Type,Dimension,Op Intensity,Num ops (MFLOP),Input_a (MB),Input_w (MB),Output (MB),Total Data (MB)
0,GEMM,"[1, 6144, 1, 4096]",0.99959,50.33165,0.00781,48.00000,0.01172,48.01953
1,Logit_MQA,"[1, 32, 1, 1024, 128, 8]",3.86415,8.38861,0.00781,2.00000,0.06250,2.07031
2,Logit_MQA,"[1, 32, 1, 256, 128, 8]",3.82090,2.09715,0.00781,0.50000,0.01562,0.52344
3,Attend_MQA,"[1, 32, 1, 1024, 128, 8]",3.86415,8.38861,0.06250,2.00000,0.00781,2.07031
4,Attend_MQA,"[1, 32, 1, 256, 128, 8]",3.82090,2.09715,0.01562,0.50000,0.00781,0.52344
5,GEMM,"[1, 4096, 1, 4096]",0.99951,33.55443,0.00781,32.00000,0.00781,32.01562
6,GEMM,"[1, 28672, 1, 4096]",0.99972,234.88102,0.00781,224.00000,0.05469,224.06250
7,GEMM,"[1, 86016, 0, 4096]",0.00000,0.00000,0.00000,672.00000,0.00000,672.00000
8,GEMM,"[1, 28672, 1, 4096]",0.99972,234.88102,0.00781,224.00000,0.05469,224.06250
9,GEMM,"[1, 86016, 0, 4096]",0.00000,0.00000,0.00000,672.00000,0.00000,672.00000
10,GEMM,"[1, 4096, 1, 28672]",0.99972,234.88102,0.05469,224.00000,0.00781,224.06250
11,GEMM,"[1, 4096, 0, 86016]",0.00000,0.00000,0.00000,672.00000,0.00000,672.00000

,MACs (MFLOP),Total Data (MB),Model Weights (MB),Unused Weights (MB),KV Cache (MB),AR data (MB),Pipe data (MB)
0,25904.02150,88749.12500,88576.00000,64512.00000,160.00000,0.50000,0.00000

In [8]:
for model in ['mixtral_7x8']:
    model_df, summary_table = prefill_moddeling(model = model, batch_size = 1,
                            input_tokens = 1024, output_tokens = 0, model_profilling=True,
                            tensor_parallel = 1, pipeline_parallel = 1) 
    print(model)
    display(model_df)
    display(summary_table)

mixtral_7x8

/Users/abambhaniya3/GenZ/src/LLM_inference/llm_prefill.py:106: UserWarning: All params would not fit on chip. System Memory Cap:40.0 GB , Weights : 86.5 GB, KV Cache:0.125

,Op Type,Dimension,Op Intensity,Num ops (MFLOP),Input_a (MB),Input_w (MB),Output (MB),Total Data (MB)
0,GEMM,"[1, 6144, 1024, 4096]",722.82353,51539.60755,8.00000,48.00000,12.00000,68.00000
1,Logit_MQA,"[1, 32, 1024, 1024, 128, 8]",110.70270,8589.93459,8.00000,2.00000,64.00000,74.00000
2,Attend_MQA,"[1, 32, 1024, 1024, 128, 8]",110.70270,8589.93459,64.00000,2.00000,8.00000,74.00000
3,GEMM,"[1, 4096, 1024, 4096]",682.66667,34359.73837,8.00000,32.00000,8.00000,48.00000
4,GEMM,"[1, 114688, 256, 4096]",240.43606,240518.16858,2.00000,896.00000,56.00000,954.00000
5,GEMM,"[1, 114688, 256, 4096]",240.43606,240518.16858,2.00000,896.00000,56.00000,954.00000
6,GEMM,"[1, 4096, 256, 114688]",240.43606,240518.16858,56.00000,896.00000,2.00000,954.00000

,MACs (MFLOP),Total Data (MB),Model Weights (MB),Unused Weights (MB),KV Cache (MB),AR data (MB),Pipe data (MB)
0,26388279.06662,100032.00000,88576.00000,0,128.00000,512.00000,0.00000

In [9]:
decode_moddeling(model = 'mixtral_7x8', batch_size = 1, Bb = 1 ,
                            input_tokens = 1024, output_tokens = 256, model_profilling=False,
                            tensor_parallel = 4, pipeline_parallel = 1, debug=True)

,MACs (MFLOP),Total Data (MB),Total Weights (MB),Parameters (MB),On-chip Memory Footprint (MB),Latency (msec),Cycles
0,201.32659,693.12402,692.00000,692.00000,168.00000,0.11541,115412.38096

,MACs (MFLOP),Total Data (MB),Total Weights (MB),Parameters (MB),On-chip Memory Footprint (MB),Latency (msec),Cycles
0,202.37517,693.38184,692.00000,692.00000,168.00000,0.11557,115567.77689

Decode Latency:4.788565338134766 msec
single_pipe_stage:4.788565338134766 msec; single_layer_time:0.14964266681671143 msec
Layers per pipeline stage:32
Error = 0.051922334376109616 in latency calc. Avg Decode Latency:4.788565338134766 msec , Latency based on last token : 4.7910516730414505 msec
Attn time:0.024634467230902776; Linear time:3.6735343933105478; AR time:1.0928828124999999; Pipeline Comm time:0.0

{'Latency': 4.788565338134766,
 'Throughput': 208.83081453150191,
 'Runtime_breakdown': [3.6735343933105478,
  0.024634467230902776,
  1.0928828124999999],
 'is_offload': False}

In [10]:
prefill_moddeling(model = 'mixtral_7x8', batch_size = 1,
                            input_tokens = 1024, output_tokens = 256, model_profilling=False,
                            tensor_parallel = 4, pipeline_parallel = 1, debug=True)

,MACs (MFLOP),Total Data (MB),Total Weights (MB),Parameters (MB),On-chip Memory Footprint (MB),Latency (msec),Cycles
0,206158.43021,798.00000,692.00000,692.00000,240.00000,0.66076,660764.19938

Prefill Latency:27.232454380307693 msec
single_pipe_stage:27.232454380307693  msec; single_layer_time:0.8510141993846154  msec
Layers per pipeline stage:32
Error = 0.0 in latency calc. Prefill Latency:27.232454380307693 msec , Latency based on last token : 27.232454380307693 msec
Attn time:0.44050946625641024; Linear time:20.70394491405128; AR time:6.088; Pipeline Comm time:0.0

{'Latency': 27.232454380307693,
 'Throughput': 36.72089140533433,
 'Runtime_breakdown': [20.70394491405128, 0.44050946625641024, 6.088],
 'is_offload': False}